### ISSUE TITLE
Can I use Java 1.7 for the latest OptlySdk? 

### ISSUE THREAD

**Issue by DavidFancy** [optimizely/java-sdk#328]
Hi, my project currently uses Java_1.7 but Optly SDK requires 1.8. Is there any way to use 1.7 with latest Optly Java SDK? If not, which version of Optly SDK support Java 1.7? Thanks.

**Comment by thomaszurkan-optimizely** [comment]
If you use an SDK prior to 3.0.0 it will support Java 7. However, you only have String attributes. 

You could fork the repo and change the gradle settings for yourself as well.
