### ISSUE TITLE
Design decision behind error log for Event and Experiment not in datafile

### ISSUE THREAD

**Issue by lucasmreis** [optimizely/java-sdk#353]
Why are these logs _errors_ and not _warnings_ or even _info_? https://github.com/optimizely/java-sdk/blob/e19dabd8586f0695b917228146b250ef5aacbe05/core-api/src/main/java/com/optimizely/ab/config/DatafileProjectConfig.java#L250

We are currently sending all Segment events to Optimizely, so this is generating a lot of errors in our logs that are not actually errors.

What are your recommendations regarding this?

Thank you in advance!

**Comment by mjc1283** [comment]
Hi @lucasmreis,

Thanks for your feedback. We will be updating the level of this log message from error to warning. In the meantime our recommendation would be to create a logback [filter] (http://logback.qos.ch/manual/filters.html#yourOwnFilter) to exclude these messages from your logs.

**Comment by lucasmreis** [comment]
Thank you very much! 👍
