### ISSUE TITLE
jcenter is going away, publish jars to another repo

### ISSUE THREAD

**Issue by Sineaggi** [optimizely/java-sdk#425]
jcenter is [going away](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Quote from gradle [issue](https://github.com/gradle/gradle/issues/16035)
> The JCenter repository is being shut down at the end of April, and as such Gradle needs to be updated to not depend on it any more and instead revert to mavenCentral()

**Comment by jaeopt** [comment]
@Sineaggi Thanks for sharing. We're aware of it and moving to MavenCentral.

**Comment by Sineaggi** [comment]
Right I did see some of the test jars [here](https://search.maven.org/search?q=com.optimizely.ab). Thanks!

**Comment by jaeopt** [comment]
@Sineaggi We switched to MavenCentral and you can find the first version (3.8.1) in there. 
We'll upload new versions to MavenCentral while serving old versions in JCenter until Feb. 01, 2022.

**Comment by Sineaggi** [comment]
@jaeopt thanks, the new library works like a treat.
